# Generated by Django 5.2.12 on 2026-03-13 15:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_banner', 6), ('featured_departments', 12), ('featured_doctors', 18), ('health_tips', 23), ('news', 29), ('emergency_banner', 34), ('testimonials', 40), ('quick_links', 45)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the hero banner', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional subtitle text', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button link URL', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('link', 3)]], {'help_text': 'Call to action button', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the banner', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('cta_button', 4), ('background_image', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Department name', 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Department description', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to department page', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Department image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 7), ('description', 8), ('link', 9), ('image', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Doctor's name", 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Doctor's specialty", 'required': True}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Doctor's photo", 'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to doctor's profile", 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 13), ('specialty', 14), ('photo', 15), ('link', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tip title', 'required': True}), 20: ('wagtail.blocks.TextBlock', (), {'help_text': 'Tip description', 'required': True}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Tip icon or image', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 19), ('description', 20), ('icon', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'News headline', 'required': True}), 25: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date', 'required': True}), 26: ('wagtail.blocks.TextBlock', (), {'help_text': 'News summary', 'required': True}), 27: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to full article', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('headline', 24), ('date', 25), ('summary', 26), ('link', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.TextBlock', (), {'help_text': 'Emergency message', 'required': True}), 31: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Emergency icon', 'required': False}), 32: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], 'help_text': 'Urgency level'}), 33: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link for more info', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('message', 30), ('icon', 31), ('urgency_level', 32), ('link', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'help_text': "Patient's name", 'required': True}), 36: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Patient's photo", 'required': False}), 37: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Testimonial text', 'required': True}), 38: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Rating out of 5', 'max_value': 5, 'min_value': 1, 'required': True}), 39: ('wagtail.blocks.StructBlock', [[('patient_name', 35), ('photo', 36), ('testimonial_text', 37), ('rating', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link label', 'required': True}), 42: ('wagtail.blocks.CharBlock', (), {'help_text': 'CSS class for icon', 'required': False}), 43: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link URL', 'required': True}), 44: ('wagtail.blocks.StructBlock', [[('label', 41), ('icon', 42), ('link', 43)]], {}), 45: ('wagtail.blocks.ListBlock', (44,), {})}),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
