# Generated by Django 5.2.12 on 2026-03-13 16:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_message',
            field=models.TextField(blank=True, help_text='Optional featured message to display prominently on the homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the page', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency hotline number', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer',
            field=wagtail.fields.StreamField([('footer', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.EmailBlock', (), {'required': True}), 5: ('wagtail.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('phone', 0), ('email', 4), ('address', 5)]], {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')]}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('platform', 7), ('url', 1), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False}), 12: ('wagtail.blocks.StructBlock', [[('quick_links', 3), ('contact_info', 6), ('emergency_hotline', 0), ('social_links', 10), ('newsletter_form', 11)]], {})}),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar',
            field=wagtail.fields.StreamField([('navbar', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Site logo', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Logo link URL', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link URL', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Sub-links for dropdown', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3), ('sub_links', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Primary navigation links'}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable search bar'}), 11: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 5)]], {'help_text': 'CTA button', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('logo', 0), ('logo_link', 1), ('nav_links', 9), ('search_enabled', 10), ('cta_button', 11)]], {})}),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support email shown in footer', max_length=254),
        ),
    ]
