# Generated by Django 5.2.12 on 2026-03-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_featured_message_homepage_page_subtitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
