# Generated by Django 5.2.12 on 2026-03-14 09:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_event_healthresource_researchpublication_department_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Department Listing Hub',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar',
            field=wagtail.fields.StreamField([('navbar', 13)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Site logo', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Logo link URL', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link URL', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short description for mega-menu', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Sub-links for dropdown', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3), ('sub_links', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Primary navigation links'}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable search bar'}), 12: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 5)]], {'help_text': 'CTA button', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('logo', 0), ('logo_link', 1), ('nav_links', 10), ('search_enabled', 11), ('cta_button', 12)]], {})}),
        ),
        migrations.CreateModel(
            name='DepartmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 4), ('expertise', 11), ('facilities', 15), ('patient_guide', 22), ('clinical_team', 23), ('rich_text', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., CARD-01', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('unit_code', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Specialized Clinical Expertise', 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., 98%', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'FontAwesome icon class', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('procedure', 0), ('description', 6), ('success_rate', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Advanced Medical Technology', 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 2), ('details', 6)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('description', 6), ('facilities', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Patient Resources & Preparation', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 17), ('download_label', 18), ('download_link', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 16), ('guides', 21)]], {}), 23: ('home.blocks.ClinicalTeamBlock', (), {}), 24: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('department_snippet', models.ForeignKey(blank=True, help_text='Link this page to a department snippet for clinical metadata sync', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.department')),
            ],
            options={
                'verbose_name': 'Clinical Department Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
